// //! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
//
// pub use super::romi_characters::Entity as RomiCharacters;
// pub use super::romi_comments::Entity as RomiComments;
// pub use super::romi_hitokotos::Entity as RomiHitokotos;
// pub use super::romi_hitokotos2::Entity as RomiHitokotos2;
// pub use super::romi_metas::Entity as RomiMetas;
// pub use super::romi_news::Entity as RomiNews;
// pub use super::romi_news_comments::Entity as RomiNewsComments;
// pub use super::romi_posts::Entity as RomiPosts;
// pub use super::romi_relationships::Entity as RomiRelationships;
// pub use super::romi_seimgs::Entity as RomiSeimgs;
// pub use super::romi_settings::Entity as RomiSettings;
// pub use super::romi_users::Entity as RomiUsers;
// pub use super::romi_views::Entity as RomiViews;
