//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "romi_fields")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub fid: u32,
    pub key: String,
    #[sea_orm(column_type = "Text")]
    pub value: String,
    pub public: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
